---
# handlers file for app
- name: Start bpmsoft service
  service: name={{app_prefix }}_{{ app_port }} state=started enabled=yes
- name: Restart bpmsoft service
  service: name={{app_prefix }}_{{ app_port }} state=restarted
- name: Restart rsyslog
  service: name=rsyslog state=restarted enabled=yes